export default [
  {
    id: 1,
    name: 'iQOO Neo 7 5G',
    img: 'assets/products/product-1.jpg',
    description: 'iQOO Neo 7 5G',
    discount: 10,
    star: 5,
    ratings: 791,
    answers: 485,
    price: 34000,
    actual_price: 38999,
  },
  {
    id: 2,
    name: 'pTron Bassbuds Duo',
    img: 'assets/products/product-2.jpg',
    description: 'pTron Bassbuds Duo TWS Earbuds with 32Hrs Total Playtime, Bluetooth 5.1 Wireless Headphones, Stereo Audio',
    discount: 69,
    star: 4,
    ratings: 791,
    answers: 485,
    price: 799,
    actual_price: 2599,
  },
  {
    id: 3,
    name: 'Noise Buds VS303',
    img: 'assets/products/product-3.jpg',
    description: 'Noise Buds VS303 in-Ear Truly Wireless Earbuds with 24H',
    discount: 53,
    star: 3,
    ratings: 791,
    answers: 485,
    price: 1399,
    actual_price: 2999,
  },
  {
    id: 4,
    name: 'Nokia C12',
    img: 'assets/products/product-4.jpg',
    description: 'Nokia C12 Android 12 (Go Edition) Smartphone, All-Day Battery, 4GB',
    discount: 20,
    star: 2,
    ratings: 791,
    answers: 485,
    price: 5999,
    actual_price: 7499,
  },
  {
    id: 5,
    name: 'Panasonic LUMIX G7',
    img: 'assets/products/product-5.jpg',
    description: 'Panasonic LUMIX G7 16.00 MP 4K Mirrorless Interchangeable Lens Camera Kit with 14-42 mm Lens (Black) with 3x Optical Zoom',
    discount: 23,
    star: 5,
    ratings: 791,
    answers: 485,
    price: 42490,
    actual_price: 54990,
  },
  {
    id: 6,
    name: 'Apple AirPods (2nd Generation)',
    img: 'assets/products/product-6.jpg',
    description: 'Apple AirPods (2nd Generation)',
    discount: 22,
    star: 3,
    ratings: 791,
    answers: 485,
    price: 10999,
    actual_price: 14100,
  },
  {
    id: 7,
    name: 'boAt Rockerz 335 Bluetooth',
    img: 'assets/products/product-7.jpg',
    description: 'boAt Rockerz 335 Bluetooth in Ear Neckband with Qualcomm aptX & CVC, Upto 30 Hours Playback, ASAP Charge, Signature Sound, IPX5 and BTv5.0(Black)',
    discount: 70,
    star: 5,
    ratings: 791,
    answers: 485,
    price: 1199,
    actual_price: 3999,
  },
  {
    id: 8,
    name: 'crocs Unisex-Adult Bayaband Clog Bpk/Cpk Clog',
    img: 'assets/products/product-8.jpg',
    description: 'crocs Unisex-Adult Bayaband Clog Bpk/Cpk Clog',
    discount: 41,
    star: 3,
    ratings: 791,
    answers: 485,
    price: 2070,
    actual_price: 3495,
  },
  {
    id: 9,
    name: 'Fastrack Reflex Beat',
    img: 'assets/products/product-9.jpg',
    description: 'New Fastrack Reflex Beat+ 1.69” UltraVU Display|500 Nits Brightness|60 Sports Modes|24*7 Heart Rate Monitor|SpO2 Monitor|Sleep Tracker|IP68 Water Resistant|Music & Camera Control',
    discount: 57,
    star: 5,
    ratings: 791,
    answers: 485,
    price: 1495,
    actual_price: 3495,
  },
  {
    id: 10,
    name: 'Gala PVA Sponge Mop',
    img: 'assets/products/product-10.jpg',
    description: 'Gala PVA Sponge Mop for Floor Cleaning, Stainless Steel butterfly mop for cleaning floor, Sponge Mop stick for Bathroom Cleaning (Blue)',
    discount: 6,
    star: 1,
    ratings: 791,
    answers: 485,
    price: 799,
    actual_price: 850,
  },
];
