export default [
  {
    id: 1,
    name: 'iQOO Neo 7 5G',
    img: 'assets/products/product-1.jpg',
    description: 'iQOO Neo 7 5G',
    discount: 10,
    star: 5,
    ratings: 791,
    answers: 485,
    price: 34000,
    actual_price: 38999,
  },
  {
    id: 2,
    name: 'pTron Bassbuds Duo',
    img: 'assets/products/product-2.jpg',
    description:
      'pTron Bassbuds Duo TWS Earbuds with 32Hrs Total Playtime, Bluetooth 5.1 Wireless Headphones, Stereo Audio',
    discount: 69,
    star: 4,
    ratings: 14513,
    answers: 541,
    price: 799,
    actual_price: 2599,
  },
  {
    id: 3,
    name: 'Noise Buds VS303',
    img: 'assets/products/product-3.jpg',
    description: 'Noise Buds VS303 in-Ear Truly Wireless Earbuds with 24H',
    discount: 53,
    star: 3,
    ratings: 4547,
    answers: 873,
    price: 1399,
    actual_price: 2999,
  },
  {
    id: 4,
    name: 'Nokia C12',
    img: 'assets/products/product-4.jpg',
    description:
      'Nokia C12 Android 12 (Go Edition) Smartphone, All-Day Battery, 4GB',
    discount: 20,
    star: 2,
    ratings: 653,
    answers: 321,
    price: 5999,
    actual_price: 7499,
  },
  {
    id: 5,
    name: 'Panasonic LUMIX G7',
    img: 'assets/products/product-5.jpg',
    description:
      'Panasonic LUMIX G7 16.00 MP 4K Mirrorless Interchangeable Lens Camera Kit with 14-42 mm Lens (Black) with 3x Optical Zoom',
    discount: 23,
    star: 5,
    ratings: 761,
    answers: 43,
    price: 42490,
    actual_price: 54990,
  },
  {
    id: 6,
    name: 'Apple AirPods (2nd Generation)',
    img: 'assets/products/product-6.jpg',
    description: 'Apple AirPods (2nd Generation)',
    discount: 22,
    star: 3,
    ratings: 9763,
    answers: 3981,
    price: 10999,
    actual_price: 14100,
  },
  {
    id: 7,
    name: 'boAt Rockerz 335 Bluetooth',
    img: 'assets/products/product-7.jpg',
    description:
      'boAt Rockerz 335 Bluetooth in Ear Neckband with Qualcomm aptX & CVC, Upto 30 Hours Playback, ASAP Charge, Signature Sound, IPX5 and BTv5.0(Black)',
    discount: 70,
    star: 4,
    ratings: 23456,
    answers: 7410,
    price: 1199,
    actual_price: 3999,
  },
  {
    id: 8,
    name: 'crocs Unisex-Adult Bayaband Clog Bpk/Cpk Clog',
    img: 'assets/products/product-8.jpg',
    description: 'crocs Unisex-Adult Bayaband Clog Bpk/Cpk Clog',
    discount: 41,
    star: 3,
    ratings: 349,
    answers: 14,
    price: 2070,
    actual_price: 3495,
  },
  {
    id: 9,
    name: 'Fastrack Reflex Beat',
    img: 'assets/products/product-9.jpg',
    description:
      'New Fastrack Reflex Beat+ 1.69” UltraVU Display|500 Nits Brightness|60 Sports Modes|24*7 Heart Rate Monitor|SpO2 Monitor|Sleep Tracker|IP68 Water Resistant|Music & Camera Control',
    discount: 57,
    star: 5,
    ratings: 8541,
    answers: 781,
    price: 1495,
    actual_price: 3495,
  },
  {
    id: 10,
    name: 'Gala PVA Sponge Mop',
    img: 'assets/products/product-10.jpg',
    description:
      'Gala PVA Sponge Mop for Floor Cleaning, Stainless Steel butterfly mop for cleaning floor, Sponge Mop stick for Bathroom Cleaning (Blue)',
    discount: 6,
    star: 1,
    ratings: 11,
    answers: 20,
    price: 799,
    actual_price: 850,
  },
  {
    id: 11,
    name: 'Apple iPhone 13 (128GB) - Midnight',
    img: 'assets/products/product-11.jpg',
    description: 'Apple iPhone 13 (128GB) - Midnight',
    discount: 22,
    star: 5,
    ratings: 14182,
    answers: 5645,
    price: 61999,
    actual_price: 79990,
  },
  {
    id: 12,
    name: 'Apple iPhone 14 Pro (1 TB) - Gold',
    img: 'assets/products/product-12.jpg',
    description: 'Apple iPhone 14 Pro (1 TB) - Gold',
    discount: 4,
    star: 4,
    ratings: 334,
    answers: 43,
    price: 173099,
    actual_price: 179900,
  },
  {
    id: 13,
    name: 'Redmi Note 11T 5G',
    img: 'assets/products/product-13.jpg',
    description:
      'Redmi Note 11T 5G (Stardust White, 8GB RAM, 128GB ROM) | Dimensity 810 5G | 33W Pro Fast Charging | Charger Included | Additional Exchange Offers| Get 2 Months of YouTube Premium Free!',
    discount: 20,
    star: 4,
    ratings: 33466,
    answers: 1000,
    price: 18499,
    actual_price: 22999,
  },
  {
    id: 14,
    name: 'Oppo A78 5G',
    img: 'assets/products/product-14.jpg',
    description:
      'Oppo A78 5G (Glowing Black, 8GB RAM, 128 Storage) | 5000 mAh Battery with 33W SUPERVOOC Charger| 50MP AI Camera | 90Hz Refresh Rate | with No Cost EMI/Additional Exchange Offers',
    discount: 14,
    star: 3,
    ratings: 1345,
    answers: 452,
    price: 18999,
    actual_price: 21999,
  },
  {
    id: 15,
    name: 'Apple iPhone 14 (128GB) - Blue',
    img: 'assets/products/product-15.jpg',
    description: 'Apple iPhone 14 (128GB) - Blue',
    discount: 5,
    star: 5,
    ratings: 86,
    answers: 31,
    price: 94900,
    actual_price: 99900,
  },
  {
    id: 16,
    name: 'INDULGE HOMES - White Vase',
    img: 'assets/products/product-16.jpg',
    description:
      'INDULGE HOMES - White Vase | Flower Vase | Pampas Grass Vase | Ceramic Vase | Round Shaped Vase',
    discount: 58,
    star: 3,
    ratings: 182,
    answers: 45,
    price: 849,
    actual_price: 1999,
  },
  {
    id: 17,
    name: 'TiedRibbons® Cycle Shape Flower Vase with Peonies Bunches',
    img: 'assets/products/product-17.jpg',
    description: 'TiedRibbons® Cycle Shape Flower Vase with Peonies Bunches',
    discount: 55,
    star: 2,
    ratings: 134,
    answers: 24,
    price: 494,
    actual_price: 1099,
  },
  {
    id: 18,
    name: 'ILU® Dream Catcher with Lights',
    img: 'assets/products/product-18.jpg',
    description:
      'ILU® Dream Catcher with Lights, Wall Hangings, Crafts, Home Décor, Handmade for Bedroom, Balcony, Garden, Party, Café',
    discount: 50,
    star: 2,
    ratings: 4754,
    answers: 137,
    price: 299,
    actual_price: 599,
  },
  {
    id: 19,
    name: 'TIED RIBBONS Resin Buddha Monk Statues',
    img: 'assets/products/product-19.jpg',
    description:
      'TIED RIBBONS Resin Buddha Monk Statues, Small, Multicolour, set of 4',
    discount: 72,
    star: 3,
    ratings: 54123,
    answers: 133,
    price: 251,
    actual_price: 899,
  },
  {
    id: 20,
    name: 'Hopdezyo Italian Gift Floor Lamp',
    img: 'assets/products/product-20.jpg',
    description:
      'Hopdezyo Italian Gift Floor Lamp with Home Decor Jute Drum Shade, Bulb, Wiring, E27 Holder Included, Pack of 1',
    discount: 66,
    star: 5,
    ratings: 1943,
    answers: 284,
    price: 1199,
    actual_price: 3500,
  },
  {
    id: 21,
    name: 'Street27® Astronaut Figurine',
    img: 'assets/products/product-21.jpg',
    description:
      'Street27® Astronaut Figurine Showpiece for Home Décor Idols for Office Desk Table Astronaut Toy for Car Dashboard',
    discount: 67,
    star: 2,
    ratings: 739,
    answers: 352,
    price: 499,
    actual_price: 1499,
  },
  {
    id: 22,
    name: 'Honor MagicBook 14, AMD Ryzen 5 5500U 14-inch',
    img: 'assets/products/product-22.jpg',
    description:
      'Honor MagicBook 14, AMD Ryzen 5 5500U 14-inch (35.56 cm) FHD IPS Anti-Glare Thin and Light Laptop (16GB/512GB PCIe SSD/Windows 11/Fingerprint Login/Metal Body',
    discount: 41,
    star: 4,
    ratings: 176543,
    answers: 5433,
    price: 44490,
    actual_price: 75999,
  },
  {
    id: 23,
    name: 'ASUS ROG Strix G17, 17.3-inch',
    img: 'assets/products/product-23.jpg',
    description:
      'ASUS ROG Strix G17, 17.3-inch (43.94 cms) FHD 144Hz, AMD Ryzen 7 4800H, RTX 3050 Ti 4GB Graphics, Gaming Laptop (16GB/1TB SSD/Windows 11//Gray/2.4 kg), G713IE-HX040W',
    discount: 25,
    star: 5,
    ratings: 6433,
    answers: 242,
    price: 90990,
    actual_price: 121990,
  },
  {
    id: 24,
    name: 'Acer Aspire 5',
    img: 'assets/products/product-24.jpg',
    description:
      'Acer Aspire 5 Gaming Laptop Intel Core i5 12th gen (12-Cores) Processor (16 GB/512 GB SSD/Win11 Home/4GB Graphics/RTX 2050) A515-57G (15.6" FHD Display, 1.8 Kg)',
    discount: 27,
    star: 2,
    ratings: 5214,
    answers: 875,
    price: 61990,
    actual_price: 84990,
  },
  {
    id: 25,
    name: 'Apple 2023 MacBook Pro Laptop',
    img: 'assets/products/product-25.jpg',
    description:
      'Apple 2023 MacBook Pro Laptop M2 Pro chip with 12‑core CPU and 19‑core GPU: 33.74 cm (16.2-inch), 16GB Unified Memory, 1TB SSD Storage. Works with iPhone/iPad; Silver',
    discount: 1,
    star: 0,
    ratings: 0,
    answers: 0,
    price: 266711,
    actual_price: 269900,
  },
  {
    id: 26,
    name: 'Regular Fit Floral Print Casual Shirt',
    img: 'assets/products/product-26.jpg',
    description: 'Regular Fit Floral Print Casual Shirt',
    discount: 50,
    star: 3,
    ratings: 11,
    answers: 0,
    price: 499,
    actual_price: 999,
  },
  {
    id: 27,
    name: 'Kiss Lip Lipstick',
    img: 'assets/products/product-27.jpg',
    description: 'Kiss Lip No Transfer Matte Lipstick (Shade 79 Caramel)',
    discount: 25,
    star: 2,
    ratings: 42,
    answers: 3,
    price: 262,
    actual_price: 349,
  },
  {
    id: 28,
    name: 'Casio',
    img: 'assets/products/product-28.jpg',
    description: `Vintage Series Digital Grey Dial Men's Watch-A-158WA-1Q`,
    discount: 0,
    star: 5,
    ratings: 664,
    answers: 43,
    price: 1695,
    actual_price: 1695,
  },
  {
    id: 29,
    name: 'RC Rexcuir',
    img: 'assets/products/product-29.jpg',
    description: 'Laptop Bags for Men and Women /15.6 inch Polyester Day',
    discount: 63,
    star: 4,
    ratings: 1323,
    answers: 231,
    price: 625,
    actual_price: 1699,
  },
  {
    id: 30,
    name: 'Urbun Fashion',
    img: 'assets/products/product-30.jpg',
    description: `Men's Printed Full Sleeve Slim Fit Cotton T-Shirt`,
    discount: 60,
    star: 2,
    ratings: 32767,
    answers: 3785,
    price: 439,
    actual_price: 1099,
  },
];
